# 下载所需品类的spu上线数和动销数据

In [2]:
import pandas as pd
from sqlalchemy import create_engine

# 连接到MySQL数据库
db_url = "mysql+pymysql://zhenggantian:123456@192.168.100.33:3306/ods"
engine = create_engine(
    db_url,
    echo=True,
    pool_size=10,
    max_overflow=20,
    pool_timeout=30,
    pool_recycle=1800,
)

data_dir = "data"

In [4]:
# 获取2024-01-01到2025-10-01之间的Litfad订单数据，并筛选特定产品分类
with engine.connect() as connection:
    query = """
    SELECT DISTINCT
    o.order_id,
    o.order_date,
    o.site_name,
    ssp.SPU,
    ssp.`状态`,
    ssp.`产品分类`,
    ssp.`主图ID`,
    ssp.`最低价格`,
    ssp.`添加时间`
FROM dws.order_product_list AS o
LEFT JOIN ods.stg_bayshop_litfad_sku AS sku 
    ON o.SKU = sku.`SKU`
LEFT JOIN ods.stg_bayshop_litfad_spu AS ssp 
    ON sku.`产品PID` = ssp.`产品PID`
WHERE o.order_date BETWEEN '2024-01-01' AND '2025-10-01'
  AND o.site_name = 'Litfad'
  AND TRIM(ssp.`产品分类`) IN (
      '90 - Coffee Tables',
      '114 - Benches',
      '88 - TV Stands & Entertainment Centers',
      '91 - End & Side Tables',
      '83 - Sofa',
      '176 - Room Dividers',
      '92 - Cabinets & Chests',
      '82 - Accent Chairs',
      '218 - Plant Stands & Tables'
  )
ORDER BY o.order_date DESC;"""
    df = pd.read_sql(query, connection)
    
# 保存
df.to_csv(f"{data_dir}/litfad_orders.csv", index=False)

2025-10-14 13:19:02,727 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-10-14 13:19:02,727 INFO sqlalchemy.engine.Engine DESCRIBE `ods`.`
    SELECT DISTINCT
    o.order_id,
    o.order_date,
    o.site_name,
    ssp.SPU,
    ssp.``状态``,
    ssp.``产品分类``,
    ssp.``主图ID``,
    ssp.``最低价格``,
    ssp.``添加时间``
FROM dws.order_product_list AS o
LEFT JOIN ods.stg_bayshop_litfad_sku AS sku
    ON o.SKU = sku.``SKU``
LEFT JOIN ods.stg_bayshop_litfad_spu AS ssp
    ON sku.``产品PID`` = ssp.``产品PID``
WHERE o.order_date BETWEEN '2024-01-01' AND '2025-10-01'
  AND o.site_name = 'Litfad'
  AND TRIM(ssp.``产品分类``) IN (
      '90 - Coffee Tables',
      '114 - Benches',
      '88 - TV Stands & Entertainment Centers',
      '91 - End & Side Tables',
      '83 - Sofa',
      '176 - Room Dividers',
      '92 - Cabinets & Chests',
      '82 - Accent Chairs',
      '218 - Plant Stands & Tables'
  )
ORDER BY o.order_date DESC;`
2025-10-14 13:19:02,727 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-10-14 13:19:02,729 INFO sqlalchemy.engine.Engine
    SELECT DISTINCT
    o.order_id,
    o.order_date,
    o.site_name,
    ssp.SPU,
    ssp.`状态`,
    ssp.`产品分类`,
    ssp.`主图ID`,
    ssp.`最低价格`,
    ssp.`添加时间`
FROM dws.order_product_list AS o
LEFT JOIN ods.stg_bayshop_litfad_sku AS sku
    ON o.SKU = sku.`SKU`
LEFT JOIN ods.stg_bayshop_litfad_spu AS ssp
    ON sku.`产品PID` = ssp.`产品PID`
WHERE o.order_date BETWEEN '2024-01-01' AND '2025-10-01'
  AND o.site_name = 'Litfad'
  AND TRIM(ssp.`产品分类`) IN (
      '90 - Coffee Tables',
      '114 - Benches',
      '88 - TV Stands & Entertainment Centers',
      '91 - End & Side Tables',
      '83 - Sofa',
      '176 - Room Dividers',
      '92 - Cabinets & Chests',
      '82 - Accent Chairs',
      '218 - Plant Stands & Tables'
  )
ORDER BY o.order_date DESC;
2025-10-14 13:19:02,729 INFO sqlalchemy.engine.Engine [raw sql] {}

2025-10-14 13:19:11,648 INFO sqlalchemy.engine.Engine ROLLBACK

In [5]:
df.head(5)

,order_id,order_date,site_name,SPU,状态,产品分类,主图ID,最低价格,添加时间
0,250930234013668,2025-09-30 23:39:45,Litfad,21957514,正常销售,90 - Coffee Tables,17300211,111.44,2025-04-22 19:41:55
1,250930234002011,2025-09-30 23:38:11,Litfad,21575377,正常销售,90 - Coffee Tables,10180845,274.12,2023-10-11 18:05:17
2,250930233202449,2025-09-30 23:31:05,Litfad,21934983,正常销售,92 - Cabinets & Chests,17043728,186.47,2025-04-10 00:35:15
3,250930232014514,2025-09-30 23:18:37,Litfad,21844733,正常销售,114 - Benches,15550414,49.02,2025-01-04 16:19:07
4,250930231213950,2025-09-30 23:12:02,Litfad,21987478,正常销售,114 - Benches,17932159,771.12,2025-06-09 00:39:12

In [6]:
# 获取所需品类的SPU列表
with engine.connect() as connection:
    spu_query = """
    SELECT `SPU`, `产品分类`, `主图ID`, `状态`, `最低价格`, `添加时间`
FROM stg_bayshop_litfad_spu AS ssp 
WHERE ssp.`添加时间` BETWEEN '2024-01-01' AND '2025-10-01'
  AND TRIM(ssp.`产品分类`) IN (
      '90 - Coffee Tables',
      '114 - Benches',
      '88 - TV Stands & Entertainment Centers',
      '91 - End & Side Tables',
      '83 - Sofa',
      '176 - Room Dividers',
      '92 - Cabinets & Chests',
      '82 - Accent Chairs',
      '218 - Plant Stands & Tables'
  )
ORDER BY ssp.`添加时间` DESC;"""

    valid_spus = pd.read_sql(spu_query, connection)

valid_spus.to_csv(f"{data_dir}/uploaded_spus.csv", index=False)

2025-10-14 13:19:51,524 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-10-14 13:19:51,524 INFO sqlalchemy.engine.Engine DESCRIBE `ods`.`
    SELECT ``SPU``, ``产品分类``, ``主图ID``, ``状态``, ``最低价格``, ``添加时间``
FROM stg_bayshop_litfad_spu AS ssp
WHERE ssp.``添加时间`` BETWEEN '2024-01-01' AND '2025-10-01'
  AND TRIM(ssp.``产品分类``) IN (
      '90 - Coffee Tables',
      '114 - Benches',
      '88 - TV Stands & Entertainment Centers',
      '91 - End & Side Tables',
      '83 - Sofa',
      '176 - Room Dividers',
      '92 - Cabinets & Chests',
      '82 - Accent Chairs',
      '218 - Plant Stands & Tables'
  )
ORDER BY ssp.``添加时间`` DESC;`
2025-10-14 13:19:51,525 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-10-14 13:19:51,526 INFO sqlalchemy.engine.Engine
    SELECT `SPU`, `产品分类`, `主图ID`, `状态`, `最低价格`, `添加时间`
FROM stg_bayshop_litfad_spu AS ssp
WHERE ssp.`添加时间` BETWEEN '2024-01-01' AND '2025-10-01'
  AND TRIM(ssp.`产品分类`) IN (
      '90 - Coffee Tables',
      '114 - Benches',
      '88 - TV Stands & Entertainment Centers',
      '91 - End & Side Tables',
      '83 - Sofa',
      '176 - Room Dividers',
      '92 - Cabinets & Chests',
      '82 - Accent Chairs',
      '218 - Plant Stands & Tables'
  )
ORDER BY ssp.`添加时间` DESC;
2025-10-14 13:19:51,527 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-10-14 13:19:51,524 INFO sqlalchemy.engine.Engine DESCRIBE `ods`.`
    SELECT ``SPU``, ``产品分类``, ``主图ID``, ``状态``, ``最低价格``, ``添加时间``
FROM stg_bayshop_litfad_spu AS ssp
WHERE ssp.``添加时间`` BETWEEN '2024-01-01' AND '2025-10-01'
  AND TRIM(ssp.``产品分类``) IN (
      '90 - Coffee Tables',
      '114 - Benches',
      '88 - TV Stands & Entertainment Centers',
      '91 - End & Side Tables',
      '83 - Sofa',
      '176 - Room Dividers',
      '92 - Cabinets & Chests',
      '82 - Accent Chairs',
      '218 - Plant Stands & Tables'
  )
ORDER BY ssp.``添加时间`` DESC;`
2025-10-14 13:19:51,525 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-10-14 13:19:51,526 INFO sqlalchemy.engine.Engine
    SELECT `SPU`, `产品分类`, `主图ID`, `状态`, `最低价格`, `添加时间`
FROM stg_bayshop_litfad_spu AS ssp
WHERE ssp.`添加时间` BETWEEN '2024-01-01' AND '2025-10-01'
  AND TRIM(ssp.`产品分类`) IN (
      '90 - Coffee Tables',
      '114 - Benches',
      '88 - TV Stands & Entertainment Centers',
      '91 - End & Side Tables',
      '83 - Sofa',
      '176 - Room Dividers',
      '92 - Cabinets & Chests',
      '82 - Accent Chairs',
      '218 - Plant Stands & Tables'
  )
ORDER BY ssp.`添加时间` DESC;
2025-10-14 13:19:51,527 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-10-14 13:19:52,652 INFO sqlalchemy.engine.Engine ROLLBACK

# 加载并计算数据

In [3]:
# 加载数据
sales_spu_df = pd.read_csv(f"{data_dir}/litfad_orders.csv")
uploaded_spu_df = pd.read_csv(f"{data_dir}/uploaded_spus.csv")

categories = uploaded_spu_df['产品分类'].unique()

In [4]:
""" 
现在是2025年10月，我们以N个月为一个周期

1. 现在来计算每个产品分类下，各自的长期动销率：
    - 计算每个产品分类在过去有订单的SPU数量（动销SPU）。
    - 计算每个产品分类在过去
    - 长期动销率 = (动销SPU / 总SPU) * 100%
    - 月均动销率 = 动销率 / N（月）
"""
result_df = pd.DataFrame(columns=['产品分类', '24年至今上线SPU数', '24年至今动销SPU数', '长期动销率(%)'])
result_list = []
for category in categories:
    total_spus = uploaded_spu_df[uploaded_spu_df['产品分类'] == category]['SPU'].nunique()
    sold_spus = sales_spu_df[sales_spu_df['产品分类'] == category]['SPU'].nunique()
    long_term_rate = (sold_spus / total_spus * 100) if total_spus > 0 else 0
    long_term_rate_per_month = long_term_rate / 21  # 21个月
    result_list.append({
        '产品分类': category,
        '24年至今上线SPU数': total_spus,
        '24年至今动销SPU数': sold_spus,
        '长期动销率(%)': round(long_term_rate, 2),
        '月均动销率(%)': round(long_term_rate_per_month, 2)
    })

result_df = pd.DataFrame(result_list)

result_df.head(12)

,产品分类,24年至今上线SPU数,24年至今动销SPU数,长期动销率(%),月均动销率(%)
0,82 - Accent Chairs,2497,707,28.31,1.35
1,218 - Plant Stands & Tables,2222,1237,55.67,2.65
2,88 - TV Stands & Entertainment Centers,4523,1623,35.88,1.71
3,176 - Room Dividers,2525,617,24.44,1.16
4,92 - Cabinets & Chests,3113,1110,35.66,1.70
5,91 - End & Side Tables,4360,2344,53.76,2.56
6,90 - Coffee Tables,9596,3426,35.70,1.70
7,83 - Sofa,3481,792,22.75,1.08
8,114 - Benches,2887,1407,48.74,2.32

In [5]:
# 以n个月为周期，计算各品类上新周期时的新品动销率
N = [3, 4, 5, 6]

for n in N:
    # 计算当前周期内的SPU动销数和上线数， 以及上一周期内的SPU动销数和上线数
    for category in categories:
        # 计算周期的起始和结束日期
        end_date = pd.to_datetime('2025-10-01')
        start_date = end_date - pd.DateOffset(months=n)
        prev_start_date = start_date - pd.DateOffset(months=n)
        prev_end_date = start_date
        # 计算当前周期内上线的SPU数量
        period_total_spus = uploaded_spu_df[
            (uploaded_spu_df['产品分类'] == category) &
            (pd.to_datetime(uploaded_spu_df['添加时间']) >= start_date) &
            (pd.to_datetime(uploaded_spu_df['添加时间']) < end_date)
        ]['SPU'].nunique()
        # 计算当前周期内动销的SPU数量
        period_sold_spus = sales_spu_df[
            (sales_spu_df['产品分类'] == category) &
            (pd.to_datetime(sales_spu_df['order_date']) >= start_date) &
            (pd.to_datetime(sales_spu_df['order_date']) < end_date)
        ]['SPU'].nunique()
        
        # 计算上一周期内上线的SPU数量
        prev_period_total_spus = uploaded_spu_df[
            (uploaded_spu_df['产品分类'] == category) &
            (pd.to_datetime(uploaded_spu_df['添加时间']) >= prev_start_date) &
            (pd.to_datetime(uploaded_spu_df['添加时间']) < prev_end_date)
        ]['SPU'].nunique()
        # 计算上一周期内动销的SPU数量
        prev_period_sold_spus = sales_spu_df[
            (sales_spu_df['产品分类'] == category) &
            (pd.to_datetime(sales_spu_df['order_date']) >= prev_start_date) &
            (pd.to_datetime(sales_spu_df['order_date']) < prev_end_date)
        ]['SPU'].nunique()

        result_df.loc[result_df['产品分类'] == category, f'近{n}个月上线SPU数'] = period_total_spus
        result_df.loc[result_df['产品分类'] == category, f'近{n}个月动销SPU数'] = period_sold_spus
        result_df.loc[result_df['产品分类'] == category, f'过去{n}到{2*n}个月上线SPU数'] = prev_period_total_spus
        result_df.loc[result_df['产品分类'] == category, f'过去{n}到{2*n}个月动销SPU数'] = prev_period_sold_spus
        
result_df.head(12)

,产品分类,24年至今上线SPU数,24年至今动销SPU数,长期动销率(%),月均动销率(%),近3个月上线SPU数,近3个月动销SPU数,过去3到6个月上线SPU数,过去3到6个月动销SPU数,近4个月上线SPU数,...,过去4到8个月上线SPU数,过去4到8个月动销SPU数,近5个月上线SPU数,近5个月动销SPU数,过去5到10个月上线SPU数,过去5到10个月动销SPU数,近6个月上线SPU数,近6个月动销SPU数,过去6到12个月上线SPU数,过去6到12个月动销SPU数
0,82 - Accent Chairs,2497,707,28.31,1.35,415.0,141.0,359.0,184.0,561.0,...,469.0,277.0,639.0,210.0,644.0,350.0,774.0,274.0,751.0,383.0
1,218 - Plant Stands & Tables,2222,1237,55.67,2.65,422.0,416.0,437.0,496.0,567.0,...,517.0,622.0,719.0,617.0,511.0,681.0,859.0,713.0,484.0,700.0
2,88 - TV Stands & Entertainment Centers,4523,1623,35.88,1.71,212.0,308.0,535.0,437.0,281.0,...,713.0,650.0,398.0,488.0,1086.0,851.0,747.0,613.0,1438.0,957.0
3,176 - Room Dividers,2525,617,24.44,1.16,551.0,186.0,459.0,200.0,725.0,...,587.0,257.0,838.0,275.0,675.0,308.0,1010.0,313.0,683.0,316.0
4,92 - Cabinets & Chests,3113,1110,35.66,1.70,369.0,271.0,367.0,321.0,496.0,...,466.0,499.0,601.0,384.0,535.0,628.0,736.0,476.0,720.0,695.0
5,91 - End & Side Tables,4360,2344,53.76,2.56,568.0,579.0,726.0,759.0,831.0,...,889.0,1072.0,1063.0,875.0,961.0,1276.0,1294.0,1040.0,1195.0,1425.0
6,90 - Coffee Tables,9596,3426,35.70,1.70,1711.0,937.0,1903.0,1127.0,2331.0,...,2609.0,1583.0,2972.0,1377.0,2905.0,1892.0,3614.0,1640.0,3216.0,2041.0
7,83 - Sofa,3481,792,22.75,1.08,418.0,137.0,372.0,179.0,555.0,...,463.0,281.0,677.0,221.0,539.0,357.0,790.0,275.0,780.0,425.0
8,114 - Benches,2887,1407,48.74,2.32,494.0,425.0,515.0,506.0,693.0,...,639.0,678.0,843.0,639.0,716.0,796.0,1009.0,747.0,860.0,831.0

In [6]:
result_df.to_csv(f"{data_dir}/litfad_category_sales_analysis.csv", index=False)

In [7]:
result_df = pd.read_csv(f"{data_dir}/litfad_category_sales_analysis.csv")

In [8]:
"""
**计算埋没因子b**：
假设理想动销率为a， 埋没因子为b，(0 < b < 1)
埋没因子b：反映该品类的SPU中后期动销率不足的因子，即上一个季度上线的SPU，在下一个季度时由于新品推流期过后，导致实际动销率受到影响的因子
理想新品动销率a：反映该品类的SPU中，经过一个季度的时间售卖后得到动销率


以n个月为周期
理想新品动销率a = 过去n到2n个月上新的spu 销售数 / 过去n到2n个月上新的spu 数
过去n到2n个月动销SPU数 = 过去n到2n个月上新的spu 销售数 +（该品类24年至今上线的总SPU数 * 月均动销率)

即，
理想新品动销率a = (过去n到2n个月动销SPU数 -（该品类24年至今上线的总SPU数 * 月均动销率)) / 过去n到2n个月上线SPU数
第n季度实际动销数 = 第n-1季度上线SPU数 * a * 2 * b + 第n季度上线SPU数 * a * 1 

ps: b越小，埋没程度越高

选品权重计算
- **埋没程度权重**：
  埋没指数 = 1 - b
  埋没权重 = 第n-1季度上线SPU数 * 埋没指数
  含义：埋没指数越大，说明埋没程度越严重，该品类需要更多翻新机会
  
- **品类权重计算**：
  综合权重 = α * 埋没权重 + β * 近12个月销售SPU数
  其中：α = 0.7（重视埋没程度），β = 0.3（兼顾销量规模）

- **挑选数量分配**：
  品类挑选数量N = round(7000 * 品类综合权重 / 所有品类综合权重总和)
"""
for n in N:
    need_columns = ['产品分类', '24年至今上线SPU数', '24年至今动销SPU数','月均动销率(%)', f'近{n}个月上线SPU数', f'近{n}个月动销SPU数', f'过去{n}到{2*n}个月上线SPU数', f'过去{n}到{2*n}个月动销SPU数']
    df = result_df[need_columns]
    prev_period_sold_of_old_spus = df['月均动销率(%)'] * df['24年至今上线SPU数'] / 100
    
    prev_period_sold_of_new_spus = df[f'过去{n}到{2*n}个月动销SPU数'] - prev_period_sold_of_old_spus
    
    # 新品动销率
    df[f'周期{n}的新品动销率(%)'] = (prev_period_sold_of_new_spus / df[f'过去{n}到{2*n}个月上线SPU数'] * 100).round(2)

    df[f'埋没因子b({n}个月为周期)'] = (df[f'近{n}个月动销SPU数'] / df[f'周期{n}的新品动销率(%)'] * 100 - df[f'近{n}个月上线SPU数']) / (2 * df[f'过去{n}到{2*n}个月上线SPU数'])
    df.to_csv(f"{data_dir}/litfad_category_sales_analysis_{n}months.csv", index=False)
    
    # 计算埋没权重和综合权重
    df[f'埋没指数({n}个月为周期)'] = 1 - df[f'埋没因子b({n}个月为周期)']
    df[f'埋没权重({n}个月为周期)'] = df[f'过去{n}到{2*n}个月上线SPU数'] * df[f'埋没指数({n}个月为周期)']
    alpha = 0.7
    beta = 0.3
    df[f'综合权重({n}个月为周期)'] = alpha * df[f'埋没权重({n}个月为周期)'] + beta * df['24年至今动销SPU数']
    total_weight = df[f'综合权重({n}个月为周期)'].sum()
    df[f'品类挑选数量({n}个月为周期)'] = (7000 * df[f'综合权重({n}个月为周期)'] / total_weight).round().astype(int)
    df.to_csv(f"{data_dir}/litfad_category_sales_analysis_{n}months_with_weights.csv", index=False)

C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'周期{n}的新品动销率(%)'] = (prev_period_sold_of_new_spus / df[f'过去{n}到{2*n}个月上线SPU数'] * 100).round(2)
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'埋没因子b({n}个月为周期)'] = (df[f'近{n}个月动销SPU数'] / df[f'周期{n}的新品动销率(%)'] * 100 - df[f'近{n}个月上线SPU数']) / (2 * df[f'过去{n}到{2*n}个月上线SPU数'])
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'埋没指数({n}个月为周期)'] = 1 - df[f'埋没因子b({n}个月为周期)']
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'埋没权重({n}个月为周期)'] = df[f'过去{n}到{2*n}个月上线SPU数'] * df[f'埋没指数({n}个月为周期)']
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'综合权重({n}个月为周期)'] = alpha * df[f'埋没权重({n}个月为周期)'] + beta * df['24年至今动销SPU数']
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'品类挑选数量({n}个月为周期)'] = (7000 * df[f'综合权重({n}个月为周期)'] / total_weight).round().astype(int)
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'周期{n}的新品动销率(%)'] = (prev_period_sold_of_new_spus / df[f'过去{n}到{2*n}个月上线SPU数'] * 100).round(2)
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'埋没因子b({n}个月为周期)'] = (df[f'近{n}个月动销SPU数'] / df[f'周期{n}的新品动销率(%)'] * 100 - df[f'近{n}个月上线SPU数']) / (2 * df[f'过去{n}到{2*n}个月上线SPU数'])
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'埋没指数({n}个月为周期)'] = 1 - df[f'埋没因子b({n}个月为周期)']
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'埋没权重({n}个月为周期)'] = df[f'过去{n}到{2*n}个月上线SPU数'] * df[f'埋没指数({n}个月为周期)']
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'综合权重({n}个月为周期)'] = alpha * df[f'埋没权重({n}个月为周期)'] + beta * df['24年至今动销SPU数']
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'品类挑选数量({n}个月为周期)'] = (7000 * df[f'综合权重({n}个月为周期)'] / total_weight).round().astype(int)
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'周期{n}的新品动销率(%)'] = (prev_period_sold_of_new_spus / df[f'过去{n}到{2*n}个月上线SPU数'] * 100).round(2)
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'埋没因子b({n}个月为周期)'] = (df[f'近{n}个月动销SPU数'] / df[f'周期{n}的新品动销率(%)'] * 100 - df[f'近{n}个月上线SPU数']) / (2 * df[f'过去{n}到{2*n}个月上线SPU数'])
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'埋没指数({n}个月为周期)'] = 1 - df[f'埋没因子b({n}个月为周期)']
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'埋没权重({n}个月为周期)'] = df[f'过去{n}到{2*n}个月上线SPU数'] * df[f'埋没指数({n}个月为周期)']
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'综合权重({n}个月为周期)'] = alpha * df[f'埋没权重({n}个月为周期)'] + beta * df['24年至今动销SPU数']
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'品类挑选数量({n}个月为周期)'] = (7000 * df[f'综合权重({n}个月为周期)'] / total_weight).round().astype(int)
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'周期{n}的新品动销率(%)'] = (prev_period_sold_of_new_spus / df[f'过去{n}到{2*n}个月上线SPU数'] * 100).round(2)
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'埋没因子b({n}个月为周期)'] = (df[f'近{n}个月动销SPU数'] / df[f'周期{n}的新品动销率(%)'] * 100 - df[f'近{n}个月上线SPU数']) / (2 * df[f'过去{n}到{2*n}个月上线SPU数'])
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'埋没指数({n}个月为周期)'] = 1 - df[f'埋没因子b({n}个月为周期)']
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'埋没权重({n}个月为周期)'] = df[f'过去{n}到{2*n}个月上线SPU数'] * df[f'埋没指数({n}个月为周期)']
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'综合权重({n}个月为周期)'] = alpha * df[f'埋没权重({n}个月为周期)'] + beta * df['24年至今动销SPU数']
C:\Users\baycheer\AppData\Local\Temp\ipykernel_15264\1484491647.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'品类挑选数量({n}个月为周期)'] = (7000 * df[f'综合权重({n}个月为周期)'] / total_weight).round().astype(int)

# SPU筛选

In [9]:
# 只保留可售状态的产品
with engine.connect() as connection:
    query_active = """
    SELECT DISTINCT SPU
    FROM ods.erp_main_tain
    WHERE `维护结果` = '可售'
    """
    valid_spus = pd.read_sql(query_active, connection)

# 过滤上传的SPU，只保留可售的
uploaded_spu_df = pd.read_csv(f"{data_dir}/uploaded_spus.csv")
valid_spu_df = uploaded_spu_df[uploaded_spu_df['SPU'].isin(valid_spus['SPU'])]
print(f"原始上传SPU数量：{len(uploaded_spu_df)} 个")
print(f"可售的上传SPU数量：{len(valid_spu_df)} 个")

2025-10-14 16:35:25,598 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2025-10-14 16:35:25,599 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-10-14 16:35:25,600 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2025-10-14 16:35:25,601 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-10-14 16:35:25,602 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2025-10-14 16:35:25,599 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-10-14 16:35:25,600 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2025-10-14 16:35:25,601 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-10-14 16:35:25,602 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2025-10-14 16:35:25,603 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-10-14 16:35:25,605 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-10-14 16:35:25,606 INFO sqlalchemy.engine.Engine DESCRIBE `ods`.`
    SELECT DISTINCT SPU
    FROM ods.erp_main_tain
    WHERE ``维护结果`` = '可售'
    `
2025-10-14 16:35:25,606 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-10-14 16:35:25,607 INFO sqlalchemy.engine.Engine
    SELECT DISTINCT SPU
    FROM ods.erp_main_tain
    WHERE `维护结果` = '可售'

2025-10-14 16:35:25,608 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-10-14 16:35:28,053 INFO sqlalchemy.engine.Engine ROLLBACK
原始上传SPU数量：35204 个
可售的上传SPU数量：21631 个

In [10]:
# 排除掉最近一个周期上线的spu，以销售额为排序依据，从各个品类中挑选出对应数量的SPU
N = 3  # 最近3个月为一个周期
end_date = pd.to_datetime('2025-10-01')
start_date = end_date - pd.DateOffset(months=N)
sales_spu_df = pd.read_csv(f"{data_dir}/litfad_orders.csv")
uploaded_spu_df = pd.read_csv(f"{data_dir}/uploaded_spus.csv")

# 过滤掉最近N个月上线的SPU
recent_spus = uploaded_spu_df[
    (pd.to_datetime(uploaded_spu_df['添加时间']) >= start_date) &
    (pd.to_datetime(uploaded_spu_df['添加时间']) < end_date)
]['SPU'].unique()
filtered_spu_df = valid_spu_df[~valid_spu_df['SPU'].isin(recent_spus)]
print(f"排除最近{N}个月上线的SPU后，可售的上传SPU数量：{len(filtered_spu_df)} 个")

排除最近3个月上线的SPU后，可售的上传SPU数量：17302 个

In [11]:
# 计算各SPU的销售量和销售额
sales_summary = sales_spu_df.groupby('SPU').size().reset_index(name='销售量')
sales_summary = sales_summary.merge(sales_spu_df[['SPU', '最低价格']].drop_duplicates(), on='SPU', how='left')
sales_summary['销售额'] = sales_summary['销售量'] * sales_summary['最低价格']
# 合并销售数据到过滤后的SPU列表
merged_df = filtered_spu_df.merge(sales_summary[['SPU', '销售量', '销售额']], on='SPU', how='left')
merged_df['销售量'] = merged_df['销售量'].fillna(0)

In [12]:
analysis_df = pd.read_csv(f"{data_dir}/litfad_category_sales_analysis_{N}months_with_weights.csv")
categories = analysis_df['产品分类'].unique()
final_selection = pd.DataFrame()
for category in categories:
    selection_count = analysis_df.loc[analysis_df['产品分类'] == category, f'品类挑选数量({N}个月为周期)'].values[0]
    category_df = merged_df[merged_df['产品分类'] == category]
    # 按销售额排序，选择前N个SPU
    top_spus = category_df.sort_values(by='销售额', ascending=False).head(selection_count)
    if len(top_spus) < selection_count:
        print(f"警告: 品类 {category} 只找到了 {len(top_spus)} 个SPU，少于预期的 {selection_count} 个。")
    print(f"品类: {category}, 挑选数量: {selection_count}, 实际挑选数量: {len(top_spus)}")
    final_selection = pd.concat([final_selection, top_spus], ignore_index=True)

final_selection.to_csv(f"{data_dir}/litfad_final_selected_spus.csv", index=False)

品类: 82 - Accent Chairs, 挑选数量: 438, 实际挑选数量: 438
品类: 218 - Plant Stands & Tables, 挑选数量: 605, 实际挑选数量: 605
品类: 88 - TV Stands & Entertainment Centers, 挑选数量: 691, 实际挑选数量: 691
品类: 176 - Room Dividers, 挑选数量: 467, 实际挑选数量: 467
品类: 92 - Cabinets & Chests, 挑选数量: 525, 实际挑选数量: 525
品类: 91 - End & Side Tables, 挑选数量: 1055, 实际挑选数量: 1055
品类: 90 - Coffee Tables, 挑选数量: 2060, 实际挑选数量: 2060
品类: 83 - Sofa, 挑选数量: 462, 实际挑选数量: 462
品类: 114 - Benches, 挑选数量: 696, 实际挑选数量: 696