In [1]:
import pandas as pd

In [4]:
excel_path = r'D:\work\auto_image\无标题.xlsx'
sheet = 'SKU产品表'
df = pd.read_excel(excel_path, sheet_name=sheet)
df.head(3)

,SPU,SKU,产品品类,产品分类,产品售价,成本价,分段,有效标记,SPU是否选择
0,210032797,2207992106,66 - Furniture,91 - End & Side Tables,172.41,25.58,200,1,1
1,210032797,2207992105,66 - Furniture,91 - End & Side Tables,154.41,27.70,200,1,1
2,210032797,2207992114,66 - Furniture,91 - End & Side Tables,154.41,27.70,200,1,1

In [7]:
selected_spus = {}
specified_categories = [
    '82 - Accent Chairs',
    '83 - Sofa',
    '88 - TV Stands & Entertainment Centers',
    '90 - Coffee Tables',
    '91 - End & Side Tables',
    '92 - Cabinets & Chests',
    '114 - Benches',
    '176 - Room Dividers',
    '218 - Plant Stands & Tables'
]
for _, row in df.iterrows():
    spu = row['SPU']
    category = row['产品分类']
    if category not in specified_categories:
        continue
    if category not in selected_spus:
        selected_spus[category]=[spu]
    else:
        if spu not in selected_spus[category]:
            selected_spus[category].append(spu)
        else:
            continue

In [13]:
all_spu_count = sum(len(spus) for spus in selected_spus.values())
print(f"Total unique SPUs across all specified categories: {all_spu_count}")
for category, spus in selected_spus.items():
    print(f"Category: {category}")
    print(len(spus))

Total unique SPUs across all specified categories: 1620
Category: 91 - End & Side Tables
118
Category: 90 - Coffee Tables
631
Category: 176 - Room Dividers
175
Category: 218 - Plant Stands & Tables
90
Category: 92 - Cabinets & Chests
134
Category: 114 - Benches
150
Category: 88 - TV Stands & Entertainment Centers
57
Category: 83 - Sofa
131
Category: 82 - Accent Chairs
134

In [11]:
df2 = pd.read_excel(r'D:\work\auto_image\8月lakiq-SKU.xlsx', sheet_name='8月lakiq-SKU')
df2.head(3)

,SPU,SKU,产品PID,产品品类,产品分类,产品售价,成本价,分段,售价有效标记,条目有效,SPU是否选择
0,210050093,2208180805,171044,21 - Furniture,25 - Coffee Tables,229.57,197.2,250,1,1,全选
1,210050093,2208180804,171044,21 - Furniture,25 - Coffee Tables,384.92,197.2,400,1,1,NaN
2,210050150,2208181488,171043,21 - Furniture,25 - Coffee Tables,3152.77,4980.0,4000,0,1,NaN

In [16]:
specified_categories = [
    '82 - Accent Chairs',
    '83 - Sofa',
    '88 - TV Stands & Entertainment Centers',
    '90 - Coffee Tables',
    '91 - End & Side Tables',
    '92 - Cabinets & Chests',
    '114 - Benches',
    '176 - Room Dividers',
    '218 - Plant Stands & Tables'
]
for _, row in df2.iterrows():
    spu = row['SPU']
    category = row['产品分类']
    if category not in specified_categories:
        continue
    if category not in selected_spus:
        selected_spus[category]=[spu]
    else:
        if spu not in selected_spus[category]:
            selected_spus[category].append(spu)
        else:
            continue

In [18]:
all_spu_count = sum(len(spus) for spus in selected_spus.values())
print(f"Total unique SPUs across all specified categories: {all_spu_count}")
for category, spus in selected_spus.items():
    print(f"Category: {category}")
    print(len(spus))

Total unique SPUs across all specified categories: 1620
Category: 91 - End & Side Tables
118
Category: 90 - Coffee Tables
631
Category: 176 - Room Dividers
175
Category: 218 - Plant Stands & Tables
90
Category: 92 - Cabinets & Chests
134
Category: 114 - Benches
150
Category: 88 - TV Stands & Entertainment Centers
57
Category: 83 - Sofa
131
Category: 82 - Accent Chairs
134

In [ ]:
df3 = pd.read_excel(r'D:\work\auto_image\10月产品.xlsx', sheet_name='10月产品')
df3.head(3)
specified_categories = [
    '82 - Accent Chairs',
    '83 - Sofa',
    '88 - TV Stands & Entertainment Centers',
    '90 - Coffee Tables',
    '91 - End & Side Tables',
    '92 - Cabinets & Chests',
    '114 - Benches',
    '176 - Room Dividers',
    '218 - Plant Stands & Tables'
]
for _, row in df3.iterrows():
    spu = row['SPU']
    category = row['产品分类']
    if category not in specified_categories:
        continue
    if category not in selected_spus:
        selected_spus[category]=[spu]
    else:
        if spu not in selected_spus[category]:
            selected_spus[category].append(spu)
        else:
            continue

In [21]:
all_spu_count = sum(len(spus) for spus in selected_spus.values())
print(f"Total unique SPUs across all specified categories: {all_spu_count}")
for category, spus in selected_spus.items():
    print(f"Category: {category}")
    print(len(spus))

Total unique SPUs across all specified categories: 3278
Category: 91 - End & Side Tables
264
Category: 90 - Coffee Tables
1209
Category: 176 - Room Dividers
361
Category: 218 - Plant Stands & Tables
129
Category: 92 - Cabinets & Chests
261
Category: 114 - Benches
339
Category: 88 - TV Stands & Entertainment Centers
138
Category: 83 - Sofa
288
Category: 82 - Accent Chairs
289

In [23]:
df4 = pd.read_excel(r'D:\work\auto_image\10月lakiq-SKU.xlsx', sheet_name='10月lakiq-SKU')
df4.head(3)
specified_categories = [
    '82 - Accent Chairs',
    '83 - Sofa',
    '88 - TV Stands & Entertainment Centers',
    '90 - Coffee Tables',
    '91 - End & Side Tables',
    '92 - Cabinets & Chests',
    '114 - Benches',
    '176 - Room Dividers',
    '218 - Plant Stands & Tables'
]
for _, row in df4.iterrows():
    spu = row['SPU']
    category = row['产品分类']
    if category not in specified_categories:
        continue
    if category not in selected_spus:
        selected_spus[category]=[spu]
    else:
        if spu not in selected_spus[category]:
            selected_spus[category].append(spu)
        else:
            continue

all_spu_count = sum(len(spus) for spus in selected_spus.values())
print(f"Total unique SPUs across all specified categories: {all_spu_count}")
for category, spus in selected_spus.items():
    print(f"Category: {category}")
    print(len(spus))

Total unique SPUs across all specified categories: 3278
Category: 91 - End & Side Tables
264
Category: 90 - Coffee Tables
1209
Category: 176 - Room Dividers
361
Category: 218 - Plant Stands & Tables
129
Category: 92 - Cabinets & Chests
261
Category: 114 - Benches
339
Category: 88 - TV Stands & Entertainment Centers
138
Category: 83 - Sofa
288
Category: 82 - Accent Chairs
289

In [24]:
with open('selected_spus.json', 'w') as f:
    import json
    json.dump(selected_spus, f, indent=4)

In [25]:
import requests
from pathlib import Path

def get_main_and_scene_images_ids(spu_id: int):
    """
    获得spu的主图和场景图片id列表
    {
        "spu_id": 123456,
        "main_image_id": "image_id_1",
        "scene_image_ids": ["image_id_2", "image_id_3"],
    }
    """
    DOWNLOAD_URL = 'https://erp.baycheer.com/api/fileAccess/getSpuImage'
    params = {
        "app_id": 392013,
        "app_token": 'URC2P3GKZGDPFAAX8M61LQ88NLRRO3T9',
        "spu_id": spu_id,
        "image_type_id": '2524'
    }
    scene_images_id_dict = {}
    scene_images_id_dict['spu_id'] = spu_id
    scene_images_id_dict['scene_image_ids'] = []
    response = requests.get(DOWNLOAD_URL, params=params)
    if response.status_code == 200:
        resp = response.json()
        if resp['code'] == 0:
            data = resp['data']
            for item in data:
                if item['is_cover_image'] == 1:
                    scene_images_id_dict['main_image_id'] = item['product_image_id']
                    continue
                if item['topic'] =='A':
                    scene_images_id_dict['scene_image_ids'].append(item['product_image_id'])
            return scene_images_id_dict
        else:
            print(f"Error in response for spu_id: {spu_id}, message: {resp['msg']}")
            return None
        
     
def get_sku_images_ids(spu_id: int):
    """
    获得spu的sku图片id列表
    {
        "spu_id": 123456,
        "sku_image_ids": ['image_id_1', 'image_id_2']
        }
    }
    """
    DOWNLOAD_URL = 'https://erp.baycheer.com/api/fileAccess/getSpuImage'
    params = {
        "app_id": 392013,
        "app_token": 'URC2P3GKZGDPFAAX8M61LQ88NLRRO3T9',
        "spu_id": spu_id,
        "image_type_id": '2528'
    }
    sku_images_id_dict = {}
    sku_images_id_dict['spu_id'] = spu_id
    sku_images_id_dict['sku_image_ids'] = []
    response = requests.get(DOWNLOAD_URL, params=params)
    if response.status_code == 200:
        resp = response.json()
        if resp['code'] == 0:
            data = resp['data']
            for item in data:
                sku_images_id_dict['sku_image_ids'].append(item['product_image_id'])
            return sku_images_id_dict
        else:
            print(f"Error in response for spu_id: {spu_id}, message: {resp['msg']}")
            return None

        


def get_images_id_with_spu_id(spu_id: int):
    """
    获得spu的所有图片id
    {
        "spu_id": 123456,
        "main_image_id": "image_id_1",
        "scene_image_ids": ["image_id_2", "image_id_3"],
        "sku_image_ids": ['image_id_4', 'image_id_5'...]
    }
    """
    main_and_scene_images_ids_dict = get_main_and_scene_images_ids(spu_id)
    sku_images_ids_dict = get_sku_images_ids(spu_id)
    if main_and_scene_images_ids_dict and sku_images_ids_dict:
        combined_dict = {
            "spu_id": spu_id,
            "main_image_id": main_and_scene_images_ids_dict.get("main_image_id"),
            "scene_image_ids": main_and_scene_images_ids_dict.get("scene_image_ids", []),
            "sku_image_ids": sku_images_ids_dict.get("sku_image_ids", [])
        }
        return combined_dict
    else:
        return None



"""
读取spu_id列表文件，获取每个spu的图片id，并以品类为组，分别保存为JSON文件
spu_file: Path - 包含spu_id列表的文件 (如: Path("D:\work\auto_image\data\litfad_final_selected_spus.csv"))
save_dir: Path - JSON文件保存目录 (如: Path("A_image_dataset/metadata/"))
"""
import json
save_dir=Path("A_image_dataset/metadata/")
# 判断保存目录是否存在，不存在则创建
if not save_dir.exists():
    save_dir.mkdir(parents=True, exist_ok=True)

for category, spu_ids in selected_spus.items():
    meta_json_path = save_dir / f"images_metadata_{category}.json"
    images_id_dicts_list = []
    for spu_id in spu_ids:
        spu_id_int = int(spu_id)
        images_id_dict = get_images_id_with_spu_id(spu_id_int)
        if images_id_dict:
            images_id_dicts_list.append(images_id_dict)
    with open(meta_json_path, "w", encoding="utf-8") as f:
        json.dump(images_id_dicts_list, f, ensure_ascii=False, indent=4)
    print(f"Saved metadata JSON for category: {category}, path: {meta_json_path}")

print("All metadata JSON files created.")

Saved metadata JSON for category: 91 - End & Side Tables, path: A_image_dataset\metadata\images_metadata_91 - End & Side Tables.json
Saved metadata JSON for category: 90 - Coffee Tables, path: A_image_dataset\metadata\images_metadata_90 - Coffee Tables.json
Saved metadata JSON for category: 176 - Room Dividers, path: A_image_dataset\metadata\images_metadata_176 - Room Dividers.json
Saved metadata JSON for category: 218 - Plant Stands & Tables, path: A_image_dataset\metadata\images_metadata_218 - Plant Stands & Tables.json
Saved metadata JSON for category: 92 - Cabinets & Chests, path: A_image_dataset\metadata\images_metadata_92 - Cabinets & Chests.json
Saved metadata JSON for category: 114 - Benches, path: A_image_dataset\metadata\images_metadata_114 - Benches.json
Saved metadata JSON for category: 88 - TV Stands & Entertainment Centers, path: A_image_dataset\metadata\images_metadata_88 - TV Stands & Entertainment Centers.json
Saved metadata JSON for category: 83 - Sofa, path: A_image_dataset\metadata\images_metadata_83 - Sofa.json
Saved metadata JSON for category: 82 - Accent Chairs, path: A_image_dataset\metadata\images_metadata_82 - Accent Chairs.json
All metadata JSON files created.